### ISSUE TITLE
Update to Swift 2.0

### ISSUE THREAD

**Issue by beltex** [practicalswift/Pythonic.swift#21]

**Comment by practicalswift** [comment]
@beltex Hi beltex, I totally agree and I'm seeking volunteers to help be bring Pythonic.swift from 1.2 to current Swift :-)

**Comment by harlanhaskins** [comment]
I'll take a stab at it!

**Comment by harlanhaskins** [comment]
Should I just remove the custom `Set` class?

**Comment by practicalswift** [comment]
The project is now compiling under Swift 2.1. Clean-ups and improvements are welcome! :-)
